# Generated by Django 4.1.7 on 2023-03-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('home_page', models.URLField(blank=True, max_length=256, null=True)),
                ('message', models.TextField()),
                ('parent_comment', models.IntegerField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
