# Generated by Django 4.1.7 on 2023-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
