# Generated by Django 4.1.7 on 2023-03-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comments_parent_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id']},
        ),
    ]
